name: Link Checker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write          # needed if you want to create issues from failures
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run lychee
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --base . --verbose --no-progress './**/*.md' './**/*.html'
          format: markdown
          output: lychee/out.md
          fail: false    # don't fail the job — we'll create an issue instead

    # (inside jobs.linkChecker.steps, after running lychee)
      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated
